version: '3.8'

services:
  policy-gui:
    build: .
    ports:
      - "8000:8000"  # Backend API
      - "3001:3001"  # Frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/app/logs 